AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  RepositoryName:
    Type: String

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${RepositoryName}
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      # RepositoryPolicyText:
      #   Version: "2012-10-17"
      #   Statement:
      #     - Effect: Allow
      #       Principal:
      #         Service: apprunner.amazonaws.com
      #       Action:
      #         - ecr:BatchGetImage
      #         - ecr:GetDownloadUrlForLayer

Outputs:
  ECRRepositoryUrl:
    Description: URL of the ECR Repository
    Value: !GetAtt ECRRepository.RepositoryUri
    Export:
      Name: !Sub '${AWS::StackName}-ECRRepositoryUrl'

  ECRRepositoryArn:
    Description: URL of the ECR Repository
    Value: !GetAtt ECRRepository.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ECRRepositoryArn'

  ECRRepositoryName:
    Description: Name of the ECR Repository
    Value: !Ref RepositoryName
