AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  AppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: GrpcAppRunnerService
      SourceConfiguration:
        ImageRepository:
          ImageIdentifier: "<your-account-id>.dkr.ecr.<region>.amazonaws.com/grpc-app:latest"
          ImageRepositoryType: ECR
        AutoDeploymentsEnabled: true
      InstanceConfiguration:
        Cpu: '1 vCPU'
        Memory: '2 GB'
        Port: 50051
      HealthCheckConfiguration:
        Protocol: TCP
        Interval: 10
        Timeout: 5
        HealthyThreshold: 3
        UnhealthyThreshold: 3

Outputs:
  AppRunnerServiceUrl:
    Description: "App Runner gRPC Service URL"
    Value: !GetAtt AppRunnerService.ServiceUrl