name: Sandbox Deployment

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}

jobs:
  deploy-ecr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: ${{ secrets.PIPELINE_EXECUTION_ROLE }}
        role-session-name: acm-repo-deploy
        role-duration-seconds: 3600
        role-skip-session-tagging: true

    - name: Build and deploy ECR template
      run: |
        sam build  \
          --template template-acm.yaml \
          --config-file samconfig.ci.yaml \
          --config-env acm

        sam deploy \
          --template template-acm.yaml \
          --config-file samconfig.ci.yaml \
          --config-env acm \
          --s3-bucket ${{ secrets.ARTIFACTS_BUCKET_NAME }} \
          --no-fail-on-empty-changeset \
          --role-arn ${{ secrets.CLOUDFORMATION_EXECUTION_ROLE }}